name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      # Setup sonar-scanner
      - name: Setup SonarQube
        uses: ./

     # Run scanner
      - name: Sonar Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=$GITHUB_WORKSPACE
            -Dsonar.verbose=true


      # # Run scanner
      # - name: Sonar Scan
      #   env:
      #     # I have added this 
      #   - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #   github_token: ${{ secrets.PAT}}
      #    # till here
      #   run: sonar-scanner
      #   with:
      #     projectBaseDir: quiz-app
      #     args: >
            
      #     -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
      #       -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
      #       -Dsonar.host.url=${{ secrets.SONAR_URL }}
      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      #       -Dsonar.sources=$GITHUB_WORKSPACE
      #       -Dsonar.verbose=true
